apiVersion: v1
kind: Pod
metadata:
  name: nginx-vod-pod
spec:
  containers:
    - name: nginx-vod
      image: nginx-vod:latest
      imagePullPolicy: Never
      ports:
      - containerPort: 80
        hostPort: 8080
      volumeMounts:
      - name: videos
        mountPath: /usr/local/videos
  volumes:
    - name: videos
      hostPath:
        path: /videos
